### Pandas DataFrame and Series

- Pandas is a powerful data manipulation library in python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. 
- A Series is a one-dimensional array-like object
- While a DataFrame is a two-dimensional, size-mutable and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
# pip install pandas

In [3]:
import pandas as pd

- Series: A pandas series is a one-dimensional array like object that can hold any data type. It is similar to a column in a table.

In [4]:
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [5]:
# Create a series from dictionary
data={'a':1, 'b':2, 'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

- DataFrame:

In [16]:
# create a DataFrame from a dictionary of list

data ={
    'Name': ['Mani', 'Ruchi', 'Dolly'],
    'Age': [31, 29, 26],
    'City': ['Mumbai', 'Manchester', 'Florida']
}

df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age        City
0   Mani   31      Mumbai
1  Ruchi   29  Manchester
2  Dolly   26     Florida
<class 'pandas.DataFrame'>

In [10]:
# Create a DataFrame from a list of dictionaries
data = [
    {'Name': 'Mani', 'Age':32, 'City':'Mumbai'},
    {'Name': 'Ruchi', 'Age':29, 'City':'Manchester'},
    {'Name': 'Dolly', 'Age':26, 'City':'Pune'},
    {'Name': 'Lucky', 'Age':29, 'City':'Nashik'},
]

df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age        City
0   Mani   32      Mumbai
1  Ruchi   29  Manchester
2  Dolly   26        Pune
3  Lucky   29      Nashik
<class 'pandas.DataFrame'>

In [11]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [12]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [18]:
# Accessing data from dataframe
df

    Name  Age        City
0   Mani   31      Mumbai
1  Ruchi   29  Manchester
2  Dolly   26     Florida

In [17]:
df['Name']

0     Mani
1    Ruchi
2    Dolly
Name: Name, dtype: str

In [26]:
df.loc[0]

Name      Mani
Age         31
City    Mumbai
Name: 0, dtype: object

In [27]:
df.iloc[0]

Name      Mani
Age         31
City    Mumbai
Name: 0, dtype: object

In [28]:
df

    Name  Age        City
0   Mani   31      Mumbai
1  Ruchi   29  Manchester
2  Dolly   26     Florida

In [30]:
df.at[2,'Age']

np.int64(26)

In [31]:
# Accessing a specified element using iat
df.iat[2,2]

'Florida'

In [32]:
df

    Name  Age        City
0   Mani   31      Mumbai
1  Ruchi   29  Manchester
2  Dolly   26     Florida

In [33]:
# Data manipulation with dataframe
df

    Name  Age        City
0   Mani   31      Mumbai
1  Ruchi   29  Manchester
2  Dolly   26     Florida

In [34]:
# adding a column
df['Salary'] = [50000, 70000, 60000]
df

    Name  Age        City  Salary
0   Mani   31      Mumbai   50000
1  Ruchi   29  Manchester   70000
2  Dolly   26     Florida   60000

In [35]:
# remove a column
df.drop('Salary', axis=1, inplace=True)

In [36]:
df

    Name  Age        City
0   Mani   31      Mumbai
1  Ruchi   29  Manchester
2  Dolly   26     Florida

In [37]:
# add age to the column
df['Age'] = df['Age']+1
df

    Name  Age        City
0   Mani   32      Mumbai
1  Ruchi   30  Manchester
2  Dolly   27     Florida

In [38]:
df.drop(0, inplace=True)

In [39]:
df

    Name  Age        City
1  Ruchi   30  Manchester
2  Dolly   27     Florida

In [40]:
df= pd.read_csv('sales_data.csv')
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [42]:
# Display the data types of each column
print(f"Data Types: \n", df.dtypes)

# Describe the dataframe
print("Statistical Summary: \n", df.describe())

Data Types:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object
Statistical Summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [43]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [45]:
# Get complete info of dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    240 non-null    int64
 1   Date              240 non-null    str
 2   Product Category  240 non-null    str
 3   Product Name      240 non-null    str
 4   Units Sold        240 non-null    int64
 5   Unit Price        240 non-null    float64
 6   Total Revenue     240 non-null    float64
 7   Region            240 non-null    str
 8   Payment Method    240 non-null    str
dtypes: float64(2), int64(2), str(5)
memory usage: 17.0 KB